{"cdb":{"internalError":"Error while accessing the customer data base","noCustomerFound":"Customer not found in database","idAlreadyExistsPleaseTryAgain":"Error occured during creation of customer data. Please try again."}}